import Head from "next/head";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import LoginForm from "./login"; // LoginForm bileşenini içe aktarın



export default function Home() {
  return (
    <>
      <Head>
        <title>Social Media</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
       
      >
        <LoginForm /> 
      </div>
    </>
  );
}
